### ISSUE TITLE
Erro ao instalar o modulo Installment Plans

### ISSUE THREAD

**Issue by bergpinheiro** [Trust-Code/trust-addons#30]
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/opt/odoo/openerp/modules/registry.py", line 194, in setup_models
    model._setup_fields(cr, SUPERUSER_ID)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3010, in _setup_fields
    field.setup(self.env)
  File "/opt/odoo/openerp/fields.py", line 468, in setup
    self._setup_related(env)
  File "/opt/odoo/openerp/fields.py", line 1367, in _setup_related
    super(Selection, self)._setup_related(env)
  File "/opt/odoo/openerp/fields.py", line 514, in _setup_related
    field = recs._fields[name]
KeyError: 'payment_order_type'

Alguem pode me ajudar?

**Comment by danimaribeiro** [comment]
Provável que seja incompatibilidade entre os branchs da OCA e estes aqui.
